version: '3'
services:
  rafaeljesusaraiva-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rafaeljesusaraiva-api/latest
    volumes:
      -  saruman-docker-data/rafaeljesusaraiva-api:/rafaeljesusaraiva-api:
  saruman-docker-data: