version: '3'
services:
  api_main:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rafaeljesusaraiva-api/latest
    volumes:
      - saruman-docker-data:/saruman-data
    ports:
     - "8010:8010"
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_DBNAME=${INFLUXDB_DBNAME}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - PORT=${PORT}
      - WEB_URL=${WEB_URL}
    network_mode: host

  api_main-01:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rafaeljesusaraiva-api/latest
    volumes:
      - saruman-docker-data:/saruman-data
    expose:
      - 8010
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_DBNAME=${INFLUXDB_DBNAME}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - PORT=${PORT}
      - WEB_URL=${WEB_URL}

  api_main-02:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rafaeljesusaraiva-api/latest
    volumes:
      - saruman-docker-data:/saruman-data
    expose:
      - 8010
    #ports:
    #  - "8010:8010"
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_DBNAME=${INFLUXDB_DBNAME}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - PORT=${PORT}
      - WEB_URL=${WEB_URL}
    #network_mode: host

  api_main-03:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rafaeljesusaraiva-api/latest
    volumes:
      - saruman-docker-data:/saruman-data
    expose:
      - 8010
    #ports:
    #  - "8010:8010"
    environment:
      - TOKEN_KEY=${TOKEN_KEY}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_DBNAME=${INFLUXDB_DBNAME}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - PORT=${PORT}
      - WEB_URL=${WEB_URL}
    #network_mode: host

  haproxy:
    image: hypriot/rpi-haproxy
    volumes:
      - saruman-docker-data:/saruman-data
      - haproxy:/haproxy-override
    command: sh -c "cp /saruman-data/haproxy-api/haproxy.cfg /haproxy-override/haproxy.cfg"
    links:
      - api_main-01
      - api_main-02
      - api_main-03
    ports:
      - "8009:8009"
    expose:
      - "8009"

volumes:
  saruman-docker-data:
    external: true
    name: saruman-docker
  haproxy:
    